LEGAL_NATURE = {
    '0000': 'Natureza Juridica Nao Informada',
    '1015': 'Orgao Publico Do Poder Executivo Federal',
    '1023': 'Orgao Publico Do Poder Executivo Estadual Ou Do Distrito Federal',
    '1031': 'Orgao Publico Do Poder Executivo Municipal',
    '1040': 'Orgao Publico Do Poder Legislativo Federal',
    '1058': 'Orgao Publico Do Poder Legislativo Estadual Ou Do Distrito Federal',
    '1066': 'Orgao Publico Do Poder Legislativo Municipal',
    '1074': 'Orgao Publico Do Poder Judiciario Federal',
    '1082': 'Orgao Publico Do Poder Judiciario Estadual',
    '1104': 'Autarquia Federal',
    '1112': 'Autarquia Estadual Ou Do Distrito Federal',
    '1120': 'Autarquia Municipal',
    '1139': 'Fundacao Publica De Direito Publico Federal',
    '1147': 'Fundacao Publica De Direito Publico Estadual Ou Do Distrito Federal',
    '1155': 'Fundacao Publica De Direito Publico Municipal',
    '1163': 'Orgao Publico Autonomo Federal',
    '1171': 'Orgao Publico Autonomo Estadual Ou Do Distrito Federal',
    '1180': 'Orgao Publico Autonomo Municipal',
    '1198': 'Comissao Polinacional',
    '1210': 'Consorcio Publico De Direito Publico (Associacao Publica)',
    '1228': 'Consorcio Publico De Direito Privado',
    '1236': 'Estado Ou Distrito Federal',
    '1244': 'Municipio',
    '1252': 'Fundacao Publica De Direito Privado Federal',
    '1260': 'Fundacao Publica De Direito Privado Estadual Ou Do Distrito Federal',
    '1279': 'Fundacao Publica De Direito Privado Municipal',
    '1287': 'Fundo Publico Da Administracao Indireta Federal',
    '1295': 'Fundo Publico Da Administracao Indireta Estadual Ou Do Distrito Federal',
    '1309': 'Fundo Publico Da Administracao Indireta Municipal',
    '1317': 'Fundo Publico Da Administracao Direta Federal',
    '1325': 'Fundo Publico Da Administracao Direta Estadual Ou Do Distrito Federal',
    '1333': 'Fundo Publico Da Administracao Direta Municipal',
    '1341': 'Uniao',
    '2011': 'Empresa Publica',
    '2038': 'Sociedade De Economia Mista',
    '2046': 'Sociedade Anonima Aberta',
    '2054': 'Sociedade Anonima Fechada',
    '2062': 'Sociedade Empresaria Limitada',
    '2070': 'Sociedade Empresaria Em Nome Coletivo',
    '2089': 'Sociedade Empresaria Em Comandita Simples',
    '2097': 'Sociedade Empresaria Em Comandita Por Acoes',
    '2100': 'Sociedade Mercantil De Capital E Industria',
    '2127': 'Sociedade Em Conta De Participacao',
    '2135': 'Empresario (Individual)',
    '2143': 'Cooperativa',
    '2151': 'Consorcio De Sociedades',
    '2160': 'Grupo De Sociedades',
    '2178': 'Estabelecimento, No Brasil, De Sociedade Estrangeira',
    '2194': 'Estabelecimento, No Brasil, De Empresa Binacional Argentino-Brasileira',
    '2216': 'Empresa Domiciliada No Exterior',
    '2224': 'Clube/Fundo De Investimento',
    '2232': 'Sociedade Simples Pura',
    '2240': 'Sociedade Simples Limitada',
    '2259': 'Sociedade Simples Em Nome Coletivo',
    '2267': 'Sociedade Simples Em Comandita Simples',
    '2275': 'Empresa Binacional',
    '2283': 'Consorcio De Empregadores',
    '2291': 'Consorcio Simples',
    '2305': 'Empresa Individual De Responsabilidade Limitada (De Natureza Empresaria)',
    '2313': 'Empresa Individual De Responsabilidade Limitada (De Natureza Simples)',
    '2321': 'Sociedade Unipessoal De Advocacia',
    '2330': 'Cooperativas De Consumo',
    '3034': 'Servico Notarial E Registral (Cartorio)',
    '3069': 'Fundacao Privada',
    '3077': 'Servico Social Autonomo',
    '3085': 'Condominio Edilicio',
    '3107': 'Comissao De Conciliacao Previa',
    '3115': 'Entidade De Mediacao E Arbitragem',
    '3131': 'Entidade Sindical',
    '3204': 'Estabelecimento, No Brasil, De Fundacao Ou Associacao Estrangeiras',
    '3212': 'Fundacao Ou Associacao Domiciliada No Exterior',
    '3220': 'Organizacao Religiosa',
    '3239': 'Comunidade Indigena',
    '3247': 'Fundo Privado',
    '3255': 'Orgao De Direcao Nacional De Partido Politico',
    '3263': 'Orgao De Direcao Regional De Partido Politico',
    '3271': 'Orgao De Direcao Local De Partido Politico',
    '3280': 'Comite Financeiro De Partido Politico',
    '3298': 'Frente Plebiscitaria Ou Referendaria',
    '3301': 'Organizacao Social (Os)',
    '3999': 'Associacao Privada',
    '4014': 'Empresa Individual Imobiliaria',
    '4090': 'Candidato A Cargo Politico Eletivo',
    '4120': 'Produtor Rural (Pessoa Fisica)',
    '5010': 'Organizacao Internacional',
    '5029': 'Representacao Diplomatica Estrangeira',
    '5037': 'Outras Instituicoes Extraterritoriais',
    '8885': 'Natureza Juridica Nao Informada'
}
