QUALIFICATION = {
    '00': 'Nao Informada',
    '05': 'Administrador',
    '08': 'Conselheiro De Administracao',
    '09': 'Curador',
    '10': 'Diretor',
    '11': 'Interventor',
    '12': 'Inventariante',
    '13': 'Liquidante',
    '14': 'Mae',
    '15': 'Pai',
    '16': 'Presidente',
    '17': 'Procurador',
    '18': 'Secretario',
    '19': 'Sindico (Condominio)',
    '20': 'Sociedade Consorciada',
    '21': 'Sociedade Filiada',
    '22': 'Socio',
    '23': 'Socio Capitalista',
    '24': 'Socio Comanditado',
    '25': 'Socio Comanditario',
    '26': 'Socio De Industria',
    '28': 'Socio-Gerente',
    '29': 'Socio Incapaz Ou Relat.Incapaz (Exceto Menor)',
    '30': 'Socio Menor (Assistido/Representado)',
    '31': 'Socio Ostensivo',
    '32': 'Tabeliao',
    '33': 'Tesoureiro',
    '34': 'Titular De Empresa Individual Imobiliaria',
    '35': 'Tutor',
    '37': 'Socio Pessoa Juridica Domiciliado No Exterior',
    '38': 'Socio Pessoa Fisica Residente No Exterior',
    '39': 'Diplomata',
    '40': 'Consul',
    '41': 'Representante De Organizacao Internacional',
    '42': 'Oficial De Registro',
    '43': 'Responsavel',
    '46': 'Ministro De Estado Das Relacoes Exteriores',
    '47': 'Socio Pessoa Fisica Residente No Brasil',
    '48': 'Socio Pessoa Juridica Domiciliado No Brasil',
    '49': 'Socio-Administrador',
    '50': 'Empresario',
    '51': 'Candidato A Cargo Politico Eletivo',
    '52': 'Socio Com Capital',
    '53': 'Socio Sem Capital',
    '54': 'Fundador',
    '55': 'Socio Comanditado Residente No Exterior',
    '56': 'Socio Comanditario Pessoa Fisica Residente No Exterior',
    '57': 'Socio Comanditario Pessoa Juridica Domiciliado No Exterior',
    '58': 'Socio Comanditario Incapaz',
    '59': 'Produtor Rural',
    '60': 'Consul Honorario',
    '61': 'Responsavel Indigena',
    '62': 'Representante Da Instituicao Extraterritorial',
    '63': 'Cotas Em Tesouraria',
    '64': 'Administrador Judicial',
    '65': 'Titular Pessoa Fisica Residente Ou Domiciliado No Brasil',
    '66': 'Titular Pessoa Fisica Residente Ou Domiciliado No Exterior',
    '67': 'Titular Pessoa Fisica Incapaz Ou Relativamente Incapaz (Exceto Menor)',
    '68': 'Titular Pessoa Fisica Menor (Assistido/Representado)',
    '69': 'Beneficiario Final',
    '70': 'Administrador Residente Ou Domiciliado No Exterior',
    '71': 'Conselheiro De Administracao Residente Ou Domiciliado No Exterior',
    '72': 'Diretor Residente Ou Domiciliado No Exterior',
    '73': 'Presidente Residente Ou Domiciliado No Exterior',
    '74': 'Socio-Administrador Residente Ou Domiciliado No Exterior',
    '75': 'Fundador Residente Ou Domiciliado No Exterior',
    '78': 'Titular Pessoa Juridica Domiciliada No Brasil',
    '79': 'Titular Pessoa Juridica Domiciliada No Exterior'
}
