REASON = {
    '00': 'Sem Motivo',
    '01': 'Extincao Por Encerramento Liquidacao Voluntaria',
    '02': 'Incorporacao',
    '03': 'Fusao',
    '04': 'Cisao Total',
    '05': 'Encerramento Da Falencia',
    '06': 'Encerramento Da Liquidacao',
    '07': 'Elevacao A Matriz',
    '08': 'Transpasse',
    '09': 'Nao Inicio De Atividade',
    '10': 'Extincao Pelo Encerramento Da Liquidacao Judicial',
    '11': 'Anulacao Por Multiciplidade',
    '12': 'Anulacao Online De Oficio',
    '13': 'Omissa Contumaz',
    '14': 'Omissa Nao Localizada',
    '15': 'Inexistencia De Fato',
    '16': 'Anulacao Por Vicios',
    '17': 'Baixa Iniciada Em Analise',
    '18': 'Interrupcao Temporaria Das Atividades',
    '21': 'Pedido De Baixa Indeferida',
    '24': 'Por Emissao Certidao Negativa',
    '28': 'Transferencia Filial Condicao Matriz',
    '31': 'Extincao-Unificacao Da Filial',
    '33': 'Transferencia Do Orgao Local A Condicao De Filial Do Orgao Regional',
    '34': 'Anulacao De Inscricao Indevida',
    '35': 'Empresa Estrangeira Aguardando Documentacao',
    '36': 'Pratica Irregular De Operacao De Comercio Exterior',
    '37': 'Baixa De Produtor Rural',
    '38': 'Baixa Deferida Pela RFB Aguardando Analise Do Convenente',
    '39': 'Baixa Deferida Pela RFB E Indeferida Pelo Convenente',
    '40': 'Baixa Indeferida Pela RFB E Aguardando Analise Do Convenente',
    '41': 'Baixa Indeferida Pela RFB E Deferida Pelo Convenente',
    '42': 'Baixa Deferida Pela RFB E Sefin, Aguardando Analise Sefaz',
    '43': 'Baixa Deferida Pela RFB, Aguardando Analise Da Sefaz E Indeferida Pela Sefin',
    '44': 'Baixa Deferida Pela RFB E Sefaz, Aguardando Analise Sefin',
    '45': 'Baixa Deferida Pela RFB, Aguardando Analise Da Sefin E Indeferida Pela Sefaz',
    '46': 'Baixa Deferida Pela RFB E Sefaz E Indeferida Pela Sefin',
    '47': 'Baixa Deferida Pela RFB E Sefin E Indeferida Pela Sefaz',
    '48': 'Baixa Indeferida Pela RFB, Agardando Analise Sefaz E Deferida Pela Sefin',
    '49': 'Baixa Indeferida Pela RFB, Aguardando Analise Da Sefaz E Indeferida Pela Sefin',
    '50': 'Baixa Indeferida Pela RFB, Deferida Pela Sefaz E Aguardando Analise Da Sefin',
    '51': 'Baixa Indeferida Pela RFB E Sefaz, Aguardando Analise Da Sefin',
    '52': 'Baixa Indeferida Pela RFB, Deferida Pela Sefaz E Indeferida Pela Sefin',
    '53': 'Baixa Indeferida Pela RFB E Sefaz E Deferida Pela Sefin',
    '54': 'Extincao - Tratamento Diferenciado Dado As Me E Epp (Lei Complementar Numero 123/2006)',
    '55': 'Deferido Pelo Convenente, Aguardando Analise Da RFB',
    '60': 'Artigo 30, Vi, Da In 748/2007',
    '61': 'Indicio Interpos. Fraudulenta',
    '62': 'Falta De Pluralidade De Socios',
    '63': 'Omissao De Declaracoes',
    '64': 'Localizacao Desconhecida',
    '66': 'Inaptidao',
    '67': 'Registro Cancelado',
    '70': 'Anulacao Por Nao Confirmado Ato De Registro Do Mei Na Junta Comercial',
    '71': 'Inaptidao (Lei 11.941/2009 Art.54)',
    '72': 'Determinacao Judicial',
    '73': 'Omissao Contumaz',
    '74': 'Inconsistencia Cadastral',
    '80': 'Baixa Registrada Na Junta, Indeferida Na RFB'
}
