# Generated by Django 3.2.5 on 2021-07-10 22:46

from django.db import migrations, models
import django.db.models.deletion
import psqlextra.manager.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsertionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished', models.BooleanField(default=False)),
                ('start', models.PositiveBigIntegerField()),
                ('end', models.PositiveBigIntegerField()),
                ('filepath', models.TextField()),
            ],
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cpf', models.CharField(help_text='CPF', max_length=11)),
                ('name', models.CharField(help_text='Nome', max_length=512)),
                ('role_initials', models.CharField(help_text='Sigla da função', max_length=512)),
                ('role_description', models.CharField(help_text='Descrição da função', max_length=512)),
                ('role_level', models.CharField(help_text='Nível da função', max_length=512)),
                ('federal_agency', models.CharField(help_text='Nome do órgão', max_length=512)),
                ('entry_date', models.DateField(help_text='Data de início das atividades')),
                ('exit_date', models.DateField(help_text='Data de término das atividades', null=True)),
                ('grace_period_end_date', models.DateField(help_text='Data de término do período de carência', null=True)),
            ],
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('finished', models.BooleanField(default=False)),
                ('folder', models.TextField()),
            ],
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['created_at'], name='cgu_pep_rel_created_57259a_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['updated_at'], name='cgu_pep_rel_updated_9c24be_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['finished'], name='cgu_pep_rel_finishe_8e473f_idx'),
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(condition=models.Q(('finished', False)), fields=('finished',), name='unique_pendind_cgu_pep_release'),
        ),
        migrations.AddField(
            model_name='person',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgu_pep.release'),
        ),
        migrations.AddField(
            model_name='insertiontask',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgu_pep.release'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['cpf'], name='cgu_pep_per_cpf_2834fe_idx'),
        ),
        migrations.AddIndex(
            model_name='person',
            index=models.Index(fields=['name'], name='cgu_pep_per_name_94b79c_idx'),
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('cpf', 'name', 'role_initials', 'role_description', 'role_level', 'federal_agency'), name='unique_person_pep'),
        ),
        migrations.AddIndex(
            model_name='insertiontask',
            index=models.Index(fields=['finished'], name='cgu_pep_ins_finishe_49f432_idx'),
        ),
    ]
