# Generated by Django 3.2.5 on 2021-07-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgu_pep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='person',
            name='unique_person_pep',
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('cpf', 'name', 'role_initials', 'role_description', 'role_level', 'federal_agency', 'entry_date'), name='unique_person_pep'),
        ),
    ]
