version: '3.9'

services:
  # Airflow
  airflow:
    build: .
    environment:
      AIRFLOW_HOME: /opt/airflow
    restart: unless-stopped
    volumes:
      - .:/opt/airflow

  # Spark
  spark:
    image: bitnami/spark:3.2.1
    environment:
      SPARK_MODE: master
    restart: unless-stopped
    ports:
      - 7077:7077
  
  spark-worker:
    image: bitnami/spark:3.2.1
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark:7077
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 6G
      replicas: 3
    depends_on:
      - spark

  # Databases
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    volumes:
      - ./.docker/postgresql:/var/lib/postgresql/data
    restart: unless-stopped
    expose:
      - 5432

  elasticsearch:
    image: elasticsearch:8.3.2
    environment:
      - xpack.security.enabled=false
      - action.destructive_requires_name=false
      - discovery.type=single-node
    restart: unless-stopped
    ports:
      - 9200:9200
    deploy:
      resources:
        limits:
          cpus: '2.5'
          memory: 4G
    volumes:
      - ./.docker/elasticsearch:/usr/share/elasticsearch/data

  # Data Lake
  minio:
    image: minio/minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    deploy:
      resources:
        limits:
          cpus: '4'
          memory: 2G
    volumes:
      - ./.docker/minio:/data
    ports:
      - 9001:9001

  # Observability
  kibana:
    image: kibana:8.3.2
    environment:
      - elasticsearch.hosts=["http://elasticsearch:9200"]
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
