# Generated by Django 3.2.5 on 2021-07-10 17:24

from django.db import migrations, models
import django.db.models.deletion
import psqlextra.manager.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_cnpj', models.CharField(help_text='CNPJ Base', max_length=8, unique=True)),
                ('name', models.CharField(help_text='Razão social', max_length=512)),
                ('legal_nature', models.CharField(help_text='Natureza jurídica', max_length=512)),
                ('qualification_person_responsible', models.CharField(help_text='Qualificação da pessoa responsável', max_length=512)),
                ('share_capital', models.PositiveBigIntegerField(help_text='Capital social da empresa')),
                ('size', models.IntegerField(choices=[(1, 'NÃO INFORMADO'), (2, 'MICRO EMPRESA'), (3, 'EMPRESA DE PEQUENO PORTE'), (5, 'DEMAIS')], help_text='Porte da empresa')),
                ('responsible_federative_entity', models.CharField(help_text='Ente federativo responsável', max_length=512)),
            ],
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cnpj', models.CharField(help_text='CNPJ da empresa', max_length=14, unique=True)),
                ('identification', models.IntegerField(choices=[(1, 'MATRIZ'), (2, 'FILIAL')], help_text='Identificador Matriz/Filial')),
                ('fantasy_name', models.CharField(help_text='Nome fantasia', max_length=512)),
                ('registration_status', models.IntegerField(choices=[(1, 'NULA'), (2, 'ATIVA'), (3, 'SUSPENSA'), (4, 'INAPTA'), (8, 'BAIXADA')], help_text='Situação cadastral')),
                ('registration_status_date', models.DateField(help_text='Data da situação cadastral', null=True)),
                ('registration_status_reason', models.CharField(help_text='Motivo da situação cadastral', max_length=512)),
                ('city_name_abroad', models.CharField(help_text='Nome da cidade no exterior', max_length=512)),
                ('country', models.CharField(help_text='País', max_length=512)),
                ('activity_start_date', models.DateField(help_text='Data de início das atividades')),
                ('main_cnae', models.CharField(help_text='CNAE Fiscal Principal', max_length=7)),
                ('street_type', models.CharField(help_text='Descrição do tipo de logradouro', max_length=512)),
                ('place', models.CharField(help_text='Logradouro onde se localiza o estabelecimento', max_length=512)),
                ('number', models.CharField(help_text='Número onde se localiza o estabelecimento', max_length=100)),
                ('complement', models.CharField(help_text='Complemento do endereço', max_length=512)),
                ('district', models.CharField(help_text='Bairro onde se localiza o estabelecimento', max_length=512)),
                ('zip_code', models.CharField(help_text='CEP do bairro onde se localiza o estabelecimento', max_length=512)),
                ('federative_unit', models.CharField(help_text='Unidade Federativa do estabelecimento', max_length=512)),
                ('county', models.CharField(help_text='Município onde se localiza o estabelecimento', max_length=512)),
                ('phone_number_1', models.CharField(help_text='Número de telefone #1', max_length=50)),
                ('phone_number_2', models.CharField(help_text='Número de telefone #2', max_length=50)),
                ('fax_number', models.CharField(help_text='Número de telefone do FAX', max_length=50)),
                ('email', models.CharField(help_text='E-mail do contribuinte', max_length=256)),
                ('special_situation', models.CharField(help_text='Situação especial da empresa', max_length=256)),
                ('special_situation_date', models.DateField(help_text='Data em que a empresa entrou em situação especial', null=True)),
            ],
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='InsertionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type', models.IntegerField(choices=[(1, 'Companies'), (2, 'Simples'), (3, 'Establishments'), (4, 'Partners')])),
                ('finished', models.BooleanField(default=False)),
                ('filepath', models.TextField(null=True)),
                ('start', models.BigIntegerField()),
                ('end', models.BigIntegerField()),
            ],
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('identifier', models.IntegerField(choices=[(1, 'PESSOA JURÍDICA'), (2, 'PESSOA FÍSICA'), (3, 'ESTRANGEIRO')], help_text='Código identificador de sócio')),
                ('name', models.CharField(help_text='Nome do sócio', max_length=512)),
                ('cpf_cnpj', models.CharField(help_text='CPF/CNPJ do sócio', max_length=14)),
                ('qualification', models.CharField(help_text='Qualificação do sócio', max_length=512)),
                ('join_date', models.DateField(help_text='Data de entrada na sociedade')),
                ('country', models.CharField(help_text='País do sócio estrangeiro', max_length=100, null=True)),
                ('legal_representative', models.CharField(help_text='CPF do representante legal', max_length=512)),
                ('legal_representative_name', models.CharField(help_text='Nome do representante legal', max_length=512)),
                ('legal_representative_qualification', models.CharField(help_text='Qualificação do representante legal', max_length=512)),
                ('age_group', models.CharField(help_text='Faixa etária do sócio', max_length=100)),
            ],
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('release_date', models.DateField(unique=True)),
                ('finished', models.BooleanField(default=False)),
                ('folder', models.CharField(max_length=512)),
            ],
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='Simples',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='rfb_cnpj.company')),
                ('base_cnpj', models.CharField(help_text='CNPJ Base', max_length=8, unique=True)),
                ('simples_option', models.IntegerField(choices=[(1, 'SIM'), (2, 'NÃO'), (3, 'OUTROS')], help_text='Optou pelo SIMPLES')),
                ('simples_option_date', models.DateField(help_text='Data que optou pelo SIMPLES', null=True)),
                ('simples_exclusion_date', models.DateField(help_text='Data de exclusão do SIMPLES', null=True)),
                ('mei_option', models.IntegerField(choices=[(1, 'SIM'), (2, 'NÃO'), (3, 'OUTROS')], help_text='Optou pelo MEI')),
                ('mei_option_date', models.DateField(help_text='Data que optou pelo MEI', null=True)),
                ('mei_exclusion_date', models.DateField(help_text='Data de exclusão do MEI', null=True)),
            ],
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['created_at'], name='rfb_cnpj_re_created_e30aac_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['updated_at'], name='rfb_cnpj_re_updated_11adeb_idx'),
        ),
        migrations.AddConstraint(
            model_name='release',
            constraint=models.UniqueConstraint(condition=models.Q(('finished', False)), fields=('finished',), name='unique_pendind_release'),
        ),
        migrations.AddField(
            model_name='partner',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfb_cnpj.company'),
        ),
        migrations.AddField(
            model_name='partner',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfb_cnpj.release'),
        ),
        migrations.AddField(
            model_name='insertiontask',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfb_cnpj.release'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfb_cnpj.company'),
        ),
        migrations.AddField(
            model_name='establishment',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfb_cnpj.release'),
        ),
        migrations.AddField(
            model_name='company',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rfb_cnpj.release'),
        ),
        migrations.AddIndex(
            model_name='simples',
            index=models.Index(fields=['created_at'], name='rfb_cnpj_si_created_4469dc_idx'),
        ),
        migrations.AddIndex(
            model_name='simples',
            index=models.Index(fields=['updated_at'], name='rfb_cnpj_si_updated_398db1_idx'),
        ),
        migrations.AddIndex(
            model_name='simples',
            index=models.Index(fields=['simples_option'], name='rfb_cnpj_si_simples_99136e_idx'),
        ),
        migrations.AddIndex(
            model_name='simples',
            index=models.Index(fields=['mei_option'], name='rfb_cnpj_si_mei_opt_91f07e_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['created_at'], name='rfb_cnpj_pa_created_6da507_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['updated_at'], name='rfb_cnpj_pa_updated_a90a7d_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['name'], name='rfb_cnpj_pa_name_731262_idx'),
        ),
        migrations.AddIndex(
            model_name='partner',
            index=models.Index(fields=['cpf_cnpj'], name='rfb_cnpj_pa_cpf_cnp_64fd75_idx'),
        ),
        migrations.AddConstraint(
            model_name='partner',
            constraint=models.UniqueConstraint(fields=('company', 'identifier', 'name', 'cpf_cnpj', 'join_date'), name='unique_partner_per_company'),
        ),
        migrations.AddIndex(
            model_name='insertiontask',
            index=models.Index(fields=['created_at'], name='rfb_cnpj_in_created_b95ad8_idx'),
        ),
        migrations.AddIndex(
            model_name='insertiontask',
            index=models.Index(fields=['updated_at'], name='rfb_cnpj_in_updated_ff99f5_idx'),
        ),
        migrations.AddIndex(
            model_name='insertiontask',
            index=models.Index(fields=['type'], name='rfb_cnpj_in_type_dbb0de_idx'),
        ),
        migrations.AddIndex(
            model_name='insertiontask',
            index=models.Index(fields=['finished'], name='rfb_cnpj_in_finishe_f30f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['created_at'], name='rfb_cnpj_es_created_fe63c0_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['updated_at'], name='rfb_cnpj_es_updated_a04dd8_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['fantasy_name'], name='rfb_cnpj_es_fantasy_99594a_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['email'], name='rfb_cnpj_es_email_ec5493_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['phone_number_1'], name='rfb_cnpj_es_phone_n_9a3763_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['phone_number_2'], name='rfb_cnpj_es_phone_n_1ad1f0_idx'),
        ),
        migrations.AddIndex(
            model_name='establishment',
            index=models.Index(fields=['fax_number'], name='rfb_cnpj_es_fax_num_269eb3_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['created_at'], name='rfb_cnpj_co_created_0e305d_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['updated_at'], name='rfb_cnpj_co_updated_c583a9_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='rfb_cnpj_co_name_76b478_idx'),
        ),
    ]
