# Generated by Django 3.2.5 on 2021-07-10 17:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfb_cnpj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='establishment',
            name='secondary_cnaes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=7), default=list, help_text='CNAEs secundários', size=None),
        ),
    ]
