# Generated by Django 3.2.5 on 2021-07-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cgu_servidores', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['position_admission_date'], name='cgu_servido_positio_2da1e8_idx'),
        ),
        migrations.AddIndex(
            model_name='pensioner',
            index=models.Index(fields=['pension_start_date'], name='cgu_servido_pension_c62aeb_idx'),
        ),
        migrations.AddIndex(
            model_name='retired',
            index=models.Index(fields=['retirement_date'], name='cgu_servido_retirem_d9a503_idx'),
        ),
    ]
