# Generated by Django 3.2.5 on 2021-07-11 16:36

from django.db import migrations, models
import django.db.models.deletion
import psqlextra.manager.manager
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsertionTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished', models.BooleanField(default=False)),
                ('type', models.IntegerField(choices=[(1, 'Payment'), (2, 'Withdraw')])),
                ('filepath', models.TextField()),
                ('start', models.PositiveBigIntegerField()),
                ('end', models.PositiveBigIntegerField()),
            ],
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_date', models.DateField(help_text='Data de referência')),
                ('competency_date', models.DateField(help_text='Data de competência')),
                ('federative_unit', models.CharField(help_text='Unidade Federativa (UF)', max_length=2)),
                ('county_siafi_code', models.CharField(help_text='Código SIAFI do município', max_length=5)),
                ('county', models.CharField(help_text='Nome do município', max_length=512)),
                ('recipient_cpf', models.CharField(help_text='CPF do favorecido', max_length=11)),
                ('recipient_nis', models.CharField(help_text='NIS do favorecido', max_length=11)),
                ('recipient_name', models.CharField(help_text='Nome do favorecido', max_length=512)),
                ('value', models.BigIntegerField(help_text='Valor da parcela')),
            ],
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('finished', models.BooleanField(default=False)),
                ('date', models.DateField(unique=True)),
                ('folder', models.TextField()),
                ('payment_uri', models.URLField()),
                ('withdraw_uri', models.URLField()),
            ],
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='Data do saque')),
                ('reference_date', models.DateField(help_text='Data de referência')),
                ('competency_date', models.DateField(help_text='Data de competência')),
                ('federative_unit', models.CharField(help_text='Unidade Federativa (UF)', max_length=2)),
                ('county_siafi_code', models.CharField(help_text='Código SIAFI do município', max_length=5)),
                ('county', models.CharField(help_text='Nome do município', max_length=512)),
                ('recipient_cpf', models.CharField(help_text='CPF do favorecido', max_length=11)),
                ('recipient_nis', models.CharField(help_text='NIS do favorecido', max_length=11)),
                ('recipient_name', models.CharField(help_text='Nome do favorecido', max_length=512)),
                ('value', models.BigIntegerField(help_text='Valor da parcela')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgu_bolsafamilia.release')),
            ],
            managers=[
                ('objects', psqlextra.manager.manager.PostgresManager()),
            ],
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['created_at'], name='cgu_bolsafa_created_dedfb0_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['updated_at'], name='cgu_bolsafa_updated_ecb492_idx'),
        ),
        migrations.AddIndex(
            model_name='release',
            index=models.Index(fields=['finished'], name='cgu_bolsafa_finishe_b4e3db_idx'),
        ),
        migrations.AddField(
            model_name='payment',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgu_bolsafamilia.release'),
        ),
        migrations.AddField(
            model_name='insertiontask',
            name='release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cgu_bolsafamilia.release'),
        ),
        migrations.AddIndex(
            model_name='withdraw',
            index=models.Index(fields=['created_at'], name='cgu_bolsafa_created_572688_idx'),
        ),
        migrations.AddIndex(
            model_name='withdraw',
            index=models.Index(fields=['updated_at'], name='cgu_bolsafa_updated_50565f_idx'),
        ),
        migrations.AddIndex(
            model_name='withdraw',
            index=models.Index(fields=['date'], name='cgu_bolsafa_date_a223fa_idx'),
        ),
        migrations.AddIndex(
            model_name='withdraw',
            index=models.Index(fields=['reference_date'], name='cgu_bolsafa_referen_d7b35f_idx'),
        ),
        migrations.AddIndex(
            model_name='withdraw',
            index=models.Index(fields=['competency_date'], name='cgu_bolsafa_compete_35b951_idx'),
        ),
        migrations.AddIndex(
            model_name='withdraw',
            index=models.Index(fields=['federative_unit'], name='cgu_bolsafa_federat_99943e_idx'),
        ),
        migrations.AddIndex(
            model_name='withdraw',
            index=models.Index(fields=['county_siafi_code'], name='cgu_bolsafa_county__152096_idx'),
        ),
        migrations.AddIndex(
            model_name='withdraw',
            index=models.Index(fields=['recipient_cpf'], name='cgu_bolsafa_recipie_215ec2_idx'),
        ),
        migrations.AddIndex(
            model_name='withdraw',
            index=models.Index(fields=['recipient_nis'], name='cgu_bolsafa_recipie_74944e_idx'),
        ),
        migrations.AddIndex(
            model_name='withdraw',
            index=models.Index(fields=['recipient_name'], name='cgu_bolsafa_recipie_43e45f_idx'),
        ),
        migrations.AddIndex(
            model_name='withdraw',
            index=models.Index(fields=['value'], name='cgu_bolsafa_value_b02a22_idx'),
        ),
        migrations.AddConstraint(
            model_name='withdraw',
            constraint=models.UniqueConstraint(fields=('date', 'reference_date', 'competency_date', 'federative_unit', 'county_siafi_code', 'recipient_cpf', 'recipient_nis', 'recipient_name', 'value'), name='unique_withdraw_entry'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['created_at'], name='cgu_bolsafa_created_fc0c6e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['updated_at'], name='cgu_bolsafa_updated_c81c23_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['reference_date'], name='cgu_bolsafa_referen_a648b6_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['competency_date'], name='cgu_bolsafa_compete_51500d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['federative_unit'], name='cgu_bolsafa_federat_2bdd0e_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['county_siafi_code'], name='cgu_bolsafa_county__09e25b_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['recipient_cpf'], name='cgu_bolsafa_recipie_c66458_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['recipient_nis'], name='cgu_bolsafa_recipie_6483f9_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['recipient_name'], name='cgu_bolsafa_recipie_22dafe_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['value'], name='cgu_bolsafa_value_d1240d_idx'),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(fields=('reference_date', 'competency_date', 'federative_unit', 'county_siafi_code', 'recipient_cpf', 'recipient_nis', 'recipient_name', 'value'), name='unique_payment_entry'),
        ),
        migrations.AddIndex(
            model_name='insertiontask',
            index=models.Index(fields=['created_at'], name='cgu_bolsafa_created_45dd65_idx'),
        ),
        migrations.AddIndex(
            model_name='insertiontask',
            index=models.Index(fields=['updated_at'], name='cgu_bolsafa_updated_8d71b8_idx'),
        ),
        migrations.AddIndex(
            model_name='insertiontask',
            index=models.Index(fields=['type'], name='cgu_bolsafa_type_2e8cb2_idx'),
        ),
        migrations.AddIndex(
            model_name='insertiontask',
            index=models.Index(fields=['finished'], name='cgu_bolsafa_finishe_5881d2_idx'),
        ),
    ]
